title: Kappuccino111
url: "https://kappuccino111.github.io"

github_username: kappuccino111
linkedin_username: akarshan111

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-picture-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_articles"
    values:
      layout: "posts"

collections:
  articles:
    output: true
    sort_by: date
    permalink: /:year/:month/:day/:slug.html

sass:
  sass_dir: _sass
  style: compressed

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"